language: node_js
node_js: 
  - node
services: 
  - postgresql
before_script: 
  - psql -c 'CREATE DATABASE paletteproducer_test; knex migrate:latest --env=test;
  knex seed:run --env=test;' -U postgres